### ISSUE TITLE
Add jira connector

### ISSUE THREAD

**Issue by rderocle** [Twenga/twgit#128] opened 2014-03-12 16:51 UTC
Add a connector for jira

**Comment by geoffroy-aubry** [comment] 2014-03-12 17:08
I agree :-)
Let us do it together! It's simple.

**Comment by geoffroy-aubry** [comment] 2014-03-12 17:09
Ah OK, it's already done :o)
I will see your PR tonight.

**Comment by geoffroy-aubry** [comment] 2014-03-12 20:41
Duplicate of #129

**Closed as completed by geoffroy-aubry** 2014-03-12 20:41 UTC
Labels: feature, duplicate
