### ISSUE TITLE
Allow to have twgit installed on a single machine but for several users

### ISSUE THREAD

**Issue by ltoussaint** [Twenga/twgit#106] opened 2013-05-28 15:05 UTC
Actually, installation of twgit copy all files in user tree (in filesystem)
So, files and folders have rights only for this user.

So, we are unable to write in files like .lastupdate for other users

To fix that, I propose to create a _.twgit_ folder in user home (/home/ltoussaint/.twgit)
and to move files which need write rights (like .lastupdate, .features_subject, .history.log and .history.error) to this folder.

Example :

``` shell
> cd /usr/share
> sudo git clone git://github.com/Twenga/twgit.git
> twgit
/usr/share/twgit_dev/twgit: line 72: /usr/share/twgit_dev/.history.error: Permission denied
tee: /usr/share/twgit_dev/.history.error: Permission denied
/usr/share/twgit_dev/twgit: line 80: /usr/share/twgit_dev/.history.log: Permission denied
tee: /usr/share/twgit_dev/.history.log: Permission denied
touch: cannot touch `/usr/share/twgit_dev/.lastupdate': Permission denied
date: /usr/share/twgit_dev/.lastupdate: No such file or directory
```

**Comment by geoffroy-aubry** [comment] 2013-05-28 15:12
Duplicate of issue #64.

**Closed as completed** 2013-05-28 15:13 UTC
Labels: duplicate
