### ISSUE TITLE
Being able to start a new branch on not clean project

### ISSUE THREAD

**Issue by Sebastien-Hanicotte** [Twenga/twgit#119] opened 2013-10-29 17:03 UTC
/\* Hope it is not a duplicate */

If the project is not clean (file uncommited, ...), we could <b>propose</b> to the user to 
1. stash the uncommited files
2. create the branch
3. unstash the uncommited files

**Comment by geoffroy-aubry** [comment] 2013-10-30 08:00
Duplicate of #99

**Closed as completed by geoffroy-aubry** 2013-10-30 08:00 UTC
Labels: feature, duplicate
